import { Recipie } from "./types";

export const recipes: Recipie[] = [
  {
    id: "Hsgh",
    title: "Spaghetti Carbonara",
    ingredients: [
      "200g spaghetti",
      "100g pancetta",
      "2 large eggs",
      "50g Pecorino cheese",
      "50g Parmesan cheese",
      "2 cloves garlic",
      "Salt",
      "Black pepper",
      "2 tbsp olive oil",
    ],
    instructions: [
      "Cook the spaghetti in salted boiling water according to package instructions.",
      "Meanwhile, heat olive oil in a large skillet over medium heat and add the pancetta.",
      "Cook until the pancetta is crispy, then add the garlic and cook for another minute.",
      "Beat the eggs in a bowl and mix in the cheeses.",
      "Drain the spaghetti, reserving some cooking water.",
      "Add the spaghetti to the skillet, remove from heat, and quickly stir in the egg and cheese mixture.",
      "Toss well, adding some reserved pasta water if needed to create a creamy sauce.",
      "Season with salt and black pepper to taste.",
    ],
    preparationTime: 20,
    isFavourite: true,
  },
  {
    id: "ytueityi",
    title: "Chicken Tikka Masala",
    ingredients: [
      "4 chicken breasts",
      "200g plain yogurt",
      "1 tbsp lemon juice",
      "2 tsp ground cumin",
      "2 tsp ground coriander",
      "1 tsp ground turmeric",
      "1 tsp ground paprika",
      "2 tsp garam masala",
      "2 cloves garlic, minced",
      "1 large onion, diced",
      "400g canned tomatoes",
      "200ml double cream",
      "2 tbsp vegetable oil",
      "Salt",
      "Fresh coriander for garnish",
    ],
    instructions: [
      "Cut the chicken breasts into bite-sized pieces and marinate in a mixture of yogurt, lemon juice, cumin, coriander, turmeric, paprika, and half of the garam masala for at least 1 hour.",
      "Heat the oil in a large pan over medium heat and add the onion. Cook until softened.",
      "Add the garlic and cook for another minute.",
      "Add the marinated chicken to the pan and cook until the chicken is browned.",
      "Add the tomatoes and remaining garam masala. Simmer for 20 minutes.",
      "Stir in the cream and simmer for another 10 minutes.",
      "Season with salt to taste and garnish with fresh coriander.",
    ],
    preparationTime: 120,
    isFavourite: true,
  },
  {
    id: "Gafrtgfsdg",
    title: "Vegetable Stir-Fry",
    ingredients: [
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 green bell pepper, sliced",
      "1 broccoli head, cut into florets",
      "2 carrots, sliced",
      "200g snow peas",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 cloves garlic, minced",
      "1 tsp grated ginger",
      "2 tbsp vegetable oil",
    ],
    instructions: [
      "Heat the vegetable oil in a large skillet or wok over high heat.",
      "Add the garlic and ginger and stir-fry for 30 seconds.",
      "Add the broccoli and carrots and stir-fry for 3-4 minutes.",
      "Add the bell peppers and snow peas and continue to stir-fry for another 3-4 minutes.",
      "Add the soy sauce and sesame oil and toss to coat the vegetables evenly.",
      "Serve immediately over rice or noodles.",
    ],
    preparationTime: 20,
    isFavourite: false,
  },
  {
    id: "Hadfghdf",
    title: "Classic Pancakes",
    ingredients: [
      "200g all-purpose flour",
      "2 tbsp sugar",
      "1 tbsp baking powder",
      "1/2 tsp salt",
      "300ml milk",
      "1 large egg",
      "2 tbsp melted butter",
      "1 tsp vanilla extract",
      "Butter or oil for cooking",
    ],
    instructions: [
      "In a large bowl, mix together the flour, sugar, baking powder, and salt.",
      "In another bowl, whisk together the milk, egg, melted butter, and vanilla extract.",
      "Pour the wet ingredients into the dry ingredients and stir until just combined.",
      "Heat a griddle or large skillet over medium heat and lightly grease with butter or oil.",
      "Pour 1/4 cup of batter onto the griddle for each pancake and cook until bubbles form on the surface.",
      "Flip and cook until the other side is golden brown.",
      "Serve warm with syrup or toppings of your choice.",
    ],
    preparationTime: 30,
    isFavourite: true,
  },
  {
    id: "o8u097ihjioejf",
    title: "Caprese Salad",
    ingredients: [
      "4 large tomatoes, sliced",
      "200g fresh mozzarella, sliced",
      "1 bunch fresh basil leaves",
      "2 tbsp extra-virgin olive oil",
      "1 tbsp balsamic vinegar",
      "Salt",
      "Black pepper",
    ],
    instructions: [
      "Arrange the tomato and mozzarella slices alternately on a serving platter.",
      "Tuck fresh basil leaves in between the tomato and mozzarella slices.",
      "Drizzle with olive oil and balsamic vinegar.",
      "Season with salt and black pepper to taste.",
    ],
    preparationTime: 10,
    isFavourite: false,
  },
];
